manifest:
  remotes:
    - name: zmkfirmware
      url_base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.6 # Oder bleib bei deiner urspr√ºnglichen Version, z.B. 0.3
      import: app/west.yml
  self:
    path: config
